"""empty message

Revision ID: 10b860563b29
Revises: 36a575108d1e
Create Date: 2014-11-02 23:14:32.001898

"""

# revision identifiers, used by Alembic.
revision = '10b860563b29'
down_revision = '36a575108d1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('create_man', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_man', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_man'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['update_man'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_teams_create_date'), 'order_teams', ['create_date'], unique=False)
    op.add_column(u'orders', sa.Column('team_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'orders', 'team_id')
    op.drop_index(op.f('ix_order_teams_create_date'), table_name='order_teams')
    op.drop_table('order_teams')
    ### end Alembic commands ###
