"""empty message

Revision ID: 12e64773fd49
Revises: 38b2dc3b3496
Create Date: 2014-11-03 19:18:56.318571

"""

# revision identifiers, used by Alembic.
revision = '12e64773fd49'
down_revision = '38b2dc3b3496'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('taobao_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_taobao_date'), 'orders', ['taobao_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_taobao_date'), table_name='orders')
    op.drop_column('orders', 'taobao_date')
    ### end Alembic commands ###
