"""empty message

Revision ID: 2e065c3ce521
Revises: 411f27d81043
Create Date: 2014-10-28 09:29:21.779308

"""

# revision identifiers, used by Alembic.
revision = '2e065c3ce521'
down_revision = '411f27d81043'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
