"""empty message

Revision ID: 2fcb580e37f0
Revises: 38b5856f89c8
Create Date: 2014-10-24 15:55:45.148843

"""

# revision identifiers, used by Alembic.
revision = '2fcb580e37f0'
down_revision = '38b5856f89c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('acter_name', sa.String(length=128), nullable=True),
    sa.Column('acter_account', sa.String(length=128), nullable=True),
    sa.Column('acter_password', sa.String(length=128), nullable=True),
    sa.Column('start_level', sa.Integer(), nullable=True),
    sa.Column('end_level', sa.Integer(), nullable=True),
    sa.Column('now_level', sa.Integer(), nullable=True),
    sa.Column('wangwang', sa.String(length=128), nullable=True),
    sa.Column('qq', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.String(length=64), nullable=True),
    sa.Column('paytype', sa.String(length=128), nullable=True),
    sa.Column('memo', sa.String(length=128), nullable=True),
    sa.Column('is_issue', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('issue_memo', sa.String(length=128), nullable=True),
    sa.Column('create_man', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_man', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['create_man'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issue_types.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['order_types.id'], ),
    sa.ForeignKeyConstraint(['update_man'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_acter_account'), 'orders', ['acter_account'], unique=False)
    op.create_index(op.f('ix_orders_acter_name'), 'orders', ['acter_name'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_acter_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_acter_account'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('order_status')
    ### end Alembic commands ###
