"""empty message

Revision ID: 342555c635c
Revises: 53a12d767c3d
Create Date: 2014-10-28 17:18:58.053699

"""

# revision identifiers, used by Alembic.
revision = '342555c635c'
down_revision = '53a12d767c3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_tasks')
    ### end Alembic commands ###
