"""empty message

Revision ID: 38b2dc3b3496
Revises: 276dba996e4b
Create Date: 2014-11-03 19:00:40.920282

"""

# revision identifiers, used by Alembic.
revision = '38b2dc3b3496'
down_revision = '276dba996e4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_warning', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('order_warning', sa.Column('create_man', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_warning_create_date'), 'order_warning', ['create_date'], unique=False)
    op.add_column('orders', sa.Column('warning_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'warning_type')
    op.drop_index(op.f('ix_order_warning_create_date'), table_name='order_warning')
    op.drop_column('order_warning', 'create_man')
    op.drop_column('order_warning', 'create_date')
    ### end Alembic commands ###
