"""empty message

Revision ID: 38b5856f89c8
Revises: 467c2cc7c559
Create Date: 2014-10-24 09:33:41.161066

"""

# revision identifiers, used by Alembic.
revision = '38b5856f89c8'
down_revision = '467c2cc7c559'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_types', sa.Column('color', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_types', 'color')
    ### end Alembic commands ###
