"""empty message

Revision ID: 411f27d81043
Revises: 2864a08a3653
Create Date: 2014-10-27 09:55:35.401001

"""

# revision identifiers, used by Alembic.
revision = '411f27d81043'
down_revision = '2864a08a3653'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('oper', sa.Integer(), nullable=True),
    sa.Column('oper_time', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['oper'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_process')
    ### end Alembic commands ###
