"""empty message

Revision ID: 53a12d767c3d
Revises: 2e065c3ce521
Create Date: 2014-10-28 10:13:47.795695

"""

# revision identifiers, used by Alembic.
revision = '53a12d767c3d'
down_revision = '2e065c3ce521'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('now_level', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('create_man', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_man', sa.Integer(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['create_man'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['update_man'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_groups_create_date'), 'order_groups', ['create_date'], unique=False)
    op.create_table('order_group_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('oper', sa.Integer(), nullable=True),
    sa.Column('oper_time', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['order_groups.id'], ),
    sa.ForeignKeyConstraint(['oper'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'orders', sa.Column('group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'orders', 'group_id')
    op.drop_table('order_group_process')
    op.drop_index(op.f('ix_order_groups_create_date'), table_name='order_groups')
    op.drop_table('order_groups')
    ### end Alembic commands ###
