"""empty message

Revision ID: 545328e43161
Revises: 2fcb580e37f0
Create Date: 2014-10-24 16:42:03.923459

"""

# revision identifiers, used by Alembic.
revision = '545328e43161'
down_revision = '2fcb580e37f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_create_date'), 'orders', ['create_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_create_date'), table_name='orders')
    ### end Alembic commands ###
