"""empty message

Revision ID: ec38fc60530
Revises: f818c505308
Create Date: 2014-10-23 00:15:37.872098

"""

# revision identifiers, used by Alembic.
revision = 'ec38fc60530'
down_revision = 'f818c505308'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
