"""empty message

Revision ID: f818c505308
Revises: 2e6130517d3e
Create Date: 2014-10-22 09:14:07.720270

"""

# revision identifiers, used by Alembic.
revision = 'f818c505308'
down_revision = '2e6130517d3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
